version = 1

test_patterns = [
  "**/*_test.go",
  "**/__test__/*"
]

exclude_patterns = [
  "doc/**",
  "**/*.pb.go",
  "**/*_pb.js",
  "**/*_pb.d.ts",
  "**/*ServiceClientPb.ts",
  "**/*ServiceClientPb.js"
]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  dependency_file_paths = ['public/']

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/quickfeed/quickfeed"

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
