name: Jest Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      -run: npm-install
      -name: jest
      -run: npx jest
