name: Jest Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.3
      - name: Run tests
        run: yarn test
